// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/v1/agents.proto

package lumov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentHealth_HealthStatus int32

const (
	AgentHealth_HEALTH_STATUS_UNSPECIFIED AgentHealth_HealthStatus = 0
	AgentHealth_HEALTH_STATUS_HEALTHY     AgentHealth_HealthStatus = 1
	AgentHealth_HEALTH_STATUS_DEGRADED    AgentHealth_HealthStatus = 2
	AgentHealth_HEALTH_STATUS_UNHEALTHY   AgentHealth_HealthStatus = 3
)

// Enum value maps for AgentHealth_HealthStatus.
var (
	AgentHealth_HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_DEGRADED",
		3: "HEALTH_STATUS_UNHEALTHY",
	}
	AgentHealth_HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_DEGRADED":    2,
		"HEALTH_STATUS_UNHEALTHY":   3,
	}
)

func (x AgentHealth_HealthStatus) Enum() *AgentHealth_HealthStatus {
	p := new(AgentHealth_HealthStatus)
	*p = x
	return p
}

func (x AgentHealth_HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentHealth_HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_agents_proto_enumTypes[0].Descriptor()
}

func (AgentHealth_HealthStatus) Type() protoreflect.EnumType {
	return &file_api_proto_v1_agents_proto_enumTypes[0]
}

func (x AgentHealth_HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentHealth_HealthStatus.Descriptor instead.
func (AgentHealth_HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_agents_proto_rawDescGZIP(), []int{4, 0}
}

type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`         // linux, darwin, windows
	Architecture  string                 `protobuf:"bytes,5,opt,name=architecture,proto3" json:"architecture,omitempty"` // amd64, arm64
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`           // Agent version
	Capabilities  []string               `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"` // cpu, memory, disk, etc.
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Kubernetes    *KubernetesMetadata    `protobuf:"bytes,9,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"` // Optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_api_proto_v1_agents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agents_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterAgentRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterAgentRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterAgentRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RegisterAgentRequest) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *RegisterAgentRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterAgentRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterAgentRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterAgentRequest) GetKubernetes() *KubernetesMetadata {
	if x != nil {
		return x.Kubernetes
	}
	return nil
}

type KubernetesMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName       string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	NodeName      string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesMetadata) Reset() {
	*x = KubernetesMetadata{}
	mi := &file_api_proto_v1_agents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesMetadata) ProtoMessage() {}

func (x *KubernetesMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesMetadata.ProtoReflect.Descriptor instead.
func (*KubernetesMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agents_proto_rawDescGZIP(), []int{1}
}

func (x *KubernetesMetadata) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubernetesMetadata) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *KubernetesMetadata) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *KubernetesMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // UUID
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_api_proto_v1_agents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agents_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterAgentResponse) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

type SendHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Health        *AgentHealth           `protobuf:"bytes,2,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendHeartbeatRequest) Reset() {
	*x = SendHeartbeatRequest{}
	mi := &file_api_proto_v1_agents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHeartbeatRequest) ProtoMessage() {}

func (x *SendHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*SendHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agents_proto_rawDescGZIP(), []int{3}
}

func (x *SendHeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SendHeartbeatRequest) GetHealth() *AgentHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

type AgentHealth struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        AgentHealth_HealthStatus `protobuf:"varint,1,opt,name=status,proto3,enum=lumo.v1.AgentHealth_HealthStatus" json:"status,omitempty"`
	Errors        map[string]string        `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Component → error message
	LastRun       *timestamppb.Timestamp   `protobuf:"bytes,3,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHealth) Reset() {
	*x = AgentHealth{}
	mi := &file_api_proto_v1_agents_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHealth) ProtoMessage() {}

func (x *AgentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agents_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHealth.ProtoReflect.Descriptor instead.
func (*AgentHealth) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agents_proto_rawDescGZIP(), []int{4}
}

func (x *AgentHealth) GetStatus() AgentHealth_HealthStatus {
	if x != nil {
		return x.Status
	}
	return AgentHealth_HEALTH_STATUS_UNSPECIFIED
}

func (x *AgentHealth) GetErrors() map[string]string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *AgentHealth) GetLastRun() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRun
	}
	return nil
}

type SendHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendHeartbeatResponse) Reset() {
	*x = SendHeartbeatResponse{}
	mi := &file_api_proto_v1_agents_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHeartbeatResponse) ProtoMessage() {}

func (x *SendHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agents_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*SendHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agents_proto_rawDescGZIP(), []int{5}
}

func (x *SendHeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *SendHeartbeatResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // online, offline, error
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Filter by labels
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_api_proto_v1_agents_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agents_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agents_proto_rawDescGZIP(), []int{6}
}

func (x *ListAgentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListAgentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAgentsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListAgentsRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_api_proto_v1_agents_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agents_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agents_proto_rawDescGZIP(), []int{7}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListAgentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type Agent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hostname        string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress       string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Platform        string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	Architecture    string                 `protobuf:"bytes,6,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Version         string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // online, offline, error
	Capabilities    []string               `protobuf:"bytes,9,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Kubernetes      *KubernetesMetadata    `protobuf:"bytes,11,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"`
	LastHeartbeatAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	RegisteredAt    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_api_proto_v1_agents_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agents_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agents_proto_rawDescGZIP(), []int{8}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Agent) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Agent) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Agent) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *Agent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Agent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Agent) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Agent) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Agent) GetKubernetes() *KubernetesMetadata {
	if x != nil {
		return x.Kubernetes
	}
	return nil
}

func (x *Agent) GetLastHeartbeatAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return nil
}

func (x *Agent) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_api_proto_v1_agents_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agents_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agents_proto_rawDescGZIP(), []int{9}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_api_proto_v1_agents_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agents_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agents_proto_rawDescGZIP(), []int{10}
}

func (x *GetAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type DeleteAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentRequest) Reset() {
	*x = DeleteAgentRequest{}
	mi := &file_api_proto_v1_agents_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentRequest) ProtoMessage() {}

func (x *DeleteAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agents_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agents_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type DeleteAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentResponse) Reset() {
	*x = DeleteAgentResponse{}
	mi := &file_api_proto_v1_agents_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentResponse) ProtoMessage() {}

func (x *DeleteAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agents_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAgentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agents_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetAgentStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStatsRequest) Reset() {
	*x = GetAgentStatsRequest{}
	mi := &file_api_proto_v1_agents_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatsRequest) ProtoMessage() {}

func (x *GetAgentStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agents_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatsRequest.ProtoReflect.Descriptor instead.
func (*GetAgentStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agents_proto_rawDescGZIP(), []int{13}
}

type GetAgentStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalAgents   int32                  `protobuf:"varint,1,opt,name=total_agents,json=totalAgents,proto3" json:"total_agents,omitempty"`
	OnlineAgents  int32                  `protobuf:"varint,2,opt,name=online_agents,json=onlineAgents,proto3" json:"online_agents,omitempty"`
	OfflineAgents int32                  `protobuf:"varint,3,opt,name=offline_agents,json=offlineAgents,proto3" json:"offline_agents,omitempty"`
	ErrorAgents   int32                  `protobuf:"varint,4,opt,name=error_agents,json=errorAgents,proto3" json:"error_agents,omitempty"`
	ByPlatform    map[string]int32       `protobuf:"bytes,5,rep,name=by_platform,json=byPlatform,proto3" json:"by_platform,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // platform → count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStatsResponse) Reset() {
	*x = GetAgentStatsResponse{}
	mi := &file_api_proto_v1_agents_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatsResponse) ProtoMessage() {}

func (x *GetAgentStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agents_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatsResponse.ProtoReflect.Descriptor instead.
func (*GetAgentStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agents_proto_rawDescGZIP(), []int{14}
}

func (x *GetAgentStatsResponse) GetTotalAgents() int32 {
	if x != nil {
		return x.TotalAgents
	}
	return 0
}

func (x *GetAgentStatsResponse) GetOnlineAgents() int32 {
	if x != nil {
		return x.OnlineAgents
	}
	return 0
}

func (x *GetAgentStatsResponse) GetOfflineAgents() int32 {
	if x != nil {
		return x.OfflineAgents
	}
	return 0
}

func (x *GetAgentStatsResponse) GetErrorAgents() int32 {
	if x != nil {
		return x.ErrorAgents
	}
	return 0
}

func (x *GetAgentStatsResponse) GetByPlatform() map[string]int32 {
	if x != nil {
		return x.ByPlatform
	}
	return nil
}

var File_api_proto_v1_agents_proto protoreflect.FileDescriptor

const file_api_proto_v1_agents_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/v1/agents.proto\x12\alumo.v1\x1a\x19api/proto/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x03\n" +
	"\x14RegisterAgentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\"\n" +
	"\farchitecture\x18\x05 \x01(\tR\farchitecture\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\x12A\n" +
	"\x06labels\x18\b \x03(\v2).lumo.v1.RegisterAgentRequest.LabelsEntryR\x06labels\x12;\n" +
	"\n" +
	"kubernetes\x18\t \x01(\v2\x1b.lumo.v1.KubernetesMetadataR\n" +
	"kubernetes\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x01\n" +
	"\x12KubernetesMetadata\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12?\n" +
	"\x06labels\x18\x04 \x03(\v2'.lumo.v1.KubernetesMetadata.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\x15RegisterAgentResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12?\n" +
	"\rregistered_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\"_\n" +
	"\x14SendHeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12,\n" +
	"\x06health\x18\x02 \x01(\v2\x14.lumo.v1.AgentHealthR\x06health\"\xf8\x02\n" +
	"\vAgentHealth\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.lumo.v1.AgentHealth.HealthStatusR\x06status\x128\n" +
	"\x06errors\x18\x02 \x03(\v2 .lumo.v1.AgentHealth.ErrorsEntryR\x06errors\x125\n" +
	"\blast_run\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\alastRun\x1a9\n" +
	"\vErrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x03\"x\n" +
	"\x15SendHeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"\xd4\x01\n" +
	"\x11ListAgentsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12>\n" +
	"\x06labels\x18\x04 \x03(\v2&.lumo.v1.ListAgentsRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x12ListAgentsResponse\x12&\n" +
	"\x06agents\x18\x01 \x03(\v2\x0e.lumo.v1.AgentR\x06agents\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xb1\x04\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12\"\n" +
	"\farchitecture\x18\x06 \x01(\tR\farchitecture\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\"\n" +
	"\fcapabilities\x18\t \x03(\tR\fcapabilities\x122\n" +
	"\x06labels\x18\n" +
	" \x03(\v2\x1a.lumo.v1.Agent.LabelsEntryR\x06labels\x12;\n" +
	"\n" +
	"kubernetes\x18\v \x01(\v2\x1b.lumo.v1.KubernetesMetadataR\n" +
	"kubernetes\x12F\n" +
	"\x11last_heartbeat_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x0flastHeartbeatAt\x12?\n" +
	"\rregistered_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\",\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"8\n" +
	"\x10GetAgentResponse\x12$\n" +
	"\x05agent\x18\x01 \x01(\v2\x0e.lumo.v1.AgentR\x05agent\"/\n" +
	"\x12DeleteAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"/\n" +
	"\x13DeleteAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x16\n" +
	"\x14GetAgentStatsRequest\"\xb9\x02\n" +
	"\x15GetAgentStatsResponse\x12!\n" +
	"\ftotal_agents\x18\x01 \x01(\x05R\vtotalAgents\x12#\n" +
	"\ronline_agents\x18\x02 \x01(\x05R\fonlineAgents\x12%\n" +
	"\x0eoffline_agents\x18\x03 \x01(\x05R\rofflineAgents\x12!\n" +
	"\ferror_agents\x18\x04 \x01(\x05R\verrorAgents\x12O\n" +
	"\vby_platform\x18\x05 \x03(\v2..lumo.v1.GetAgentStatsResponse.ByPlatformEntryR\n" +
	"byPlatform\x1a=\n" +
	"\x0fByPlatformEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012\xd1\x03\n" +
	"\rAgentsService\x12N\n" +
	"\rRegisterAgent\x12\x1d.lumo.v1.RegisterAgentRequest\x1a\x1e.lumo.v1.RegisterAgentResponse\x12N\n" +
	"\rSendHeartbeat\x12\x1d.lumo.v1.SendHeartbeatRequest\x1a\x1e.lumo.v1.SendHeartbeatResponse\x12E\n" +
	"\n" +
	"ListAgents\x12\x1a.lumo.v1.ListAgentsRequest\x1a\x1b.lumo.v1.ListAgentsResponse\x12?\n" +
	"\bGetAgent\x12\x18.lumo.v1.GetAgentRequest\x1a\x19.lumo.v1.GetAgentResponse\x12H\n" +
	"\vDeleteAgent\x12\x1b.lumo.v1.DeleteAgentRequest\x1a\x1c.lumo.v1.DeleteAgentResponse\x12N\n" +
	"\rGetAgentStats\x12\x1d.lumo.v1.GetAgentStatsRequest\x1a\x1e.lumo.v1.GetAgentStatsResponseB-Z+github.com/ignacio/lumo/api/proto/v1;lumov1b\x06proto3"

var (
	file_api_proto_v1_agents_proto_rawDescOnce sync.Once
	file_api_proto_v1_agents_proto_rawDescData []byte
)

func file_api_proto_v1_agents_proto_rawDescGZIP() []byte {
	file_api_proto_v1_agents_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_agents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_agents_proto_rawDesc), len(file_api_proto_v1_agents_proto_rawDesc)))
	})
	return file_api_proto_v1_agents_proto_rawDescData
}

var file_api_proto_v1_agents_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_agents_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_proto_v1_agents_proto_goTypes = []any{
	(AgentHealth_HealthStatus)(0), // 0: lumo.v1.AgentHealth.HealthStatus
	(*RegisterAgentRequest)(nil),  // 1: lumo.v1.RegisterAgentRequest
	(*KubernetesMetadata)(nil),    // 2: lumo.v1.KubernetesMetadata
	(*RegisterAgentResponse)(nil), // 3: lumo.v1.RegisterAgentResponse
	(*SendHeartbeatRequest)(nil),  // 4: lumo.v1.SendHeartbeatRequest
	(*AgentHealth)(nil),           // 5: lumo.v1.AgentHealth
	(*SendHeartbeatResponse)(nil), // 6: lumo.v1.SendHeartbeatResponse
	(*ListAgentsRequest)(nil),     // 7: lumo.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),    // 8: lumo.v1.ListAgentsResponse
	(*Agent)(nil),                 // 9: lumo.v1.Agent
	(*GetAgentRequest)(nil),       // 10: lumo.v1.GetAgentRequest
	(*GetAgentResponse)(nil),      // 11: lumo.v1.GetAgentResponse
	(*DeleteAgentRequest)(nil),    // 12: lumo.v1.DeleteAgentRequest
	(*DeleteAgentResponse)(nil),   // 13: lumo.v1.DeleteAgentResponse
	(*GetAgentStatsRequest)(nil),  // 14: lumo.v1.GetAgentStatsRequest
	(*GetAgentStatsResponse)(nil), // 15: lumo.v1.GetAgentStatsResponse
	nil,                           // 16: lumo.v1.RegisterAgentRequest.LabelsEntry
	nil,                           // 17: lumo.v1.KubernetesMetadata.LabelsEntry
	nil,                           // 18: lumo.v1.AgentHealth.ErrorsEntry
	nil,                           // 19: lumo.v1.ListAgentsRequest.LabelsEntry
	nil,                           // 20: lumo.v1.Agent.LabelsEntry
	nil,                           // 21: lumo.v1.GetAgentStatsResponse.ByPlatformEntry
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
}
var file_api_proto_v1_agents_proto_depIdxs = []int32{
	16, // 0: lumo.v1.RegisterAgentRequest.labels:type_name -> lumo.v1.RegisterAgentRequest.LabelsEntry
	2,  // 1: lumo.v1.RegisterAgentRequest.kubernetes:type_name -> lumo.v1.KubernetesMetadata
	17, // 2: lumo.v1.KubernetesMetadata.labels:type_name -> lumo.v1.KubernetesMetadata.LabelsEntry
	22, // 3: lumo.v1.RegisterAgentResponse.registered_at:type_name -> google.protobuf.Timestamp
	5,  // 4: lumo.v1.SendHeartbeatRequest.health:type_name -> lumo.v1.AgentHealth
	0,  // 5: lumo.v1.AgentHealth.status:type_name -> lumo.v1.AgentHealth.HealthStatus
	18, // 6: lumo.v1.AgentHealth.errors:type_name -> lumo.v1.AgentHealth.ErrorsEntry
	22, // 7: lumo.v1.AgentHealth.last_run:type_name -> google.protobuf.Timestamp
	22, // 8: lumo.v1.SendHeartbeatResponse.server_time:type_name -> google.protobuf.Timestamp
	19, // 9: lumo.v1.ListAgentsRequest.labels:type_name -> lumo.v1.ListAgentsRequest.LabelsEntry
	9,  // 10: lumo.v1.ListAgentsResponse.agents:type_name -> lumo.v1.Agent
	20, // 11: lumo.v1.Agent.labels:type_name -> lumo.v1.Agent.LabelsEntry
	2,  // 12: lumo.v1.Agent.kubernetes:type_name -> lumo.v1.KubernetesMetadata
	22, // 13: lumo.v1.Agent.last_heartbeat_at:type_name -> google.protobuf.Timestamp
	22, // 14: lumo.v1.Agent.registered_at:type_name -> google.protobuf.Timestamp
	9,  // 15: lumo.v1.GetAgentResponse.agent:type_name -> lumo.v1.Agent
	21, // 16: lumo.v1.GetAgentStatsResponse.by_platform:type_name -> lumo.v1.GetAgentStatsResponse.ByPlatformEntry
	1,  // 17: lumo.v1.AgentsService.RegisterAgent:input_type -> lumo.v1.RegisterAgentRequest
	4,  // 18: lumo.v1.AgentsService.SendHeartbeat:input_type -> lumo.v1.SendHeartbeatRequest
	7,  // 19: lumo.v1.AgentsService.ListAgents:input_type -> lumo.v1.ListAgentsRequest
	10, // 20: lumo.v1.AgentsService.GetAgent:input_type -> lumo.v1.GetAgentRequest
	12, // 21: lumo.v1.AgentsService.DeleteAgent:input_type -> lumo.v1.DeleteAgentRequest
	14, // 22: lumo.v1.AgentsService.GetAgentStats:input_type -> lumo.v1.GetAgentStatsRequest
	3,  // 23: lumo.v1.AgentsService.RegisterAgent:output_type -> lumo.v1.RegisterAgentResponse
	6,  // 24: lumo.v1.AgentsService.SendHeartbeat:output_type -> lumo.v1.SendHeartbeatResponse
	8,  // 25: lumo.v1.AgentsService.ListAgents:output_type -> lumo.v1.ListAgentsResponse
	11, // 26: lumo.v1.AgentsService.GetAgent:output_type -> lumo.v1.GetAgentResponse
	13, // 27: lumo.v1.AgentsService.DeleteAgent:output_type -> lumo.v1.DeleteAgentResponse
	15, // 28: lumo.v1.AgentsService.GetAgentStats:output_type -> lumo.v1.GetAgentStatsResponse
	23, // [23:29] is the sub-list for method output_type
	17, // [17:23] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_api_proto_v1_agents_proto_init() }
func file_api_proto_v1_agents_proto_init() {
	if File_api_proto_v1_agents_proto != nil {
		return
	}
	file_api_proto_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_agents_proto_rawDesc), len(file_api_proto_v1_agents_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_agents_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_agents_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_agents_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_agents_proto_msgTypes,
	}.Build()
	File_api_proto_v1_agents_proto = out.File
	file_api_proto_v1_agents_proto_goTypes = nil
	file_api_proto_v1_agents_proto_depIdxs = nil
}
