// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/v1/diagnostics.proto

package lumov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiagnosticsService_RunDiagnostics_FullMethodName       = "/lumo.v1.DiagnosticsService/RunDiagnostics"
	DiagnosticsService_GetDiagnosticsResult_FullMethodName = "/lumo.v1.DiagnosticsService/GetDiagnosticsResult"
	DiagnosticsService_StreamDiagnostics_FullMethodName    = "/lumo.v1.DiagnosticsService/StreamDiagnostics"
	DiagnosticsService_ListDiagnostics_FullMethodName      = "/lumo.v1.DiagnosticsService/ListDiagnostics"
)

// DiagnosticsServiceClient is the client API for DiagnosticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiagnosticsServiceClient interface {
	// Run diagnostics asynchronously, returns job ID
	RunDiagnostics(ctx context.Context, in *RunDiagnosticsRequest, opts ...grpc.CallOption) (*RunDiagnosticsResponse, error)
	// Get diagnostic result by job ID
	GetDiagnosticsResult(ctx context.Context, in *GetDiagnosticsResultRequest, opts ...grpc.CallOption) (*GetDiagnosticsResultResponse, error)
	// Stream diagnostic progress (real-time updates)
	StreamDiagnostics(ctx context.Context, in *StreamDiagnosticsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DiagnosticsEvent], error)
	// List recent diagnostics
	ListDiagnostics(ctx context.Context, in *ListDiagnosticsRequest, opts ...grpc.CallOption) (*ListDiagnosticsResponse, error)
}

type diagnosticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiagnosticsServiceClient(cc grpc.ClientConnInterface) DiagnosticsServiceClient {
	return &diagnosticsServiceClient{cc}
}

func (c *diagnosticsServiceClient) RunDiagnostics(ctx context.Context, in *RunDiagnosticsRequest, opts ...grpc.CallOption) (*RunDiagnosticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunDiagnosticsResponse)
	err := c.cc.Invoke(ctx, DiagnosticsService_RunDiagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosticsServiceClient) GetDiagnosticsResult(ctx context.Context, in *GetDiagnosticsResultRequest, opts ...grpc.CallOption) (*GetDiagnosticsResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiagnosticsResultResponse)
	err := c.cc.Invoke(ctx, DiagnosticsService_GetDiagnosticsResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosticsServiceClient) StreamDiagnostics(ctx context.Context, in *StreamDiagnosticsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DiagnosticsEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DiagnosticsService_ServiceDesc.Streams[0], DiagnosticsService_StreamDiagnostics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamDiagnosticsRequest, DiagnosticsEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DiagnosticsService_StreamDiagnosticsClient = grpc.ServerStreamingClient[DiagnosticsEvent]

func (c *diagnosticsServiceClient) ListDiagnostics(ctx context.Context, in *ListDiagnosticsRequest, opts ...grpc.CallOption) (*ListDiagnosticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDiagnosticsResponse)
	err := c.cc.Invoke(ctx, DiagnosticsService_ListDiagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiagnosticsServiceServer is the server API for DiagnosticsService service.
// All implementations must embed UnimplementedDiagnosticsServiceServer
// for forward compatibility.
type DiagnosticsServiceServer interface {
	// Run diagnostics asynchronously, returns job ID
	RunDiagnostics(context.Context, *RunDiagnosticsRequest) (*RunDiagnosticsResponse, error)
	// Get diagnostic result by job ID
	GetDiagnosticsResult(context.Context, *GetDiagnosticsResultRequest) (*GetDiagnosticsResultResponse, error)
	// Stream diagnostic progress (real-time updates)
	StreamDiagnostics(*StreamDiagnosticsRequest, grpc.ServerStreamingServer[DiagnosticsEvent]) error
	// List recent diagnostics
	ListDiagnostics(context.Context, *ListDiagnosticsRequest) (*ListDiagnosticsResponse, error)
	mustEmbedUnimplementedDiagnosticsServiceServer()
}

// UnimplementedDiagnosticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiagnosticsServiceServer struct{}

func (UnimplementedDiagnosticsServiceServer) RunDiagnostics(context.Context, *RunDiagnosticsRequest) (*RunDiagnosticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunDiagnostics not implemented")
}
func (UnimplementedDiagnosticsServiceServer) GetDiagnosticsResult(context.Context, *GetDiagnosticsResultRequest) (*GetDiagnosticsResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiagnosticsResult not implemented")
}
func (UnimplementedDiagnosticsServiceServer) StreamDiagnostics(*StreamDiagnosticsRequest, grpc.ServerStreamingServer[DiagnosticsEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamDiagnostics not implemented")
}
func (UnimplementedDiagnosticsServiceServer) ListDiagnostics(context.Context, *ListDiagnosticsRequest) (*ListDiagnosticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDiagnostics not implemented")
}
func (UnimplementedDiagnosticsServiceServer) mustEmbedUnimplementedDiagnosticsServiceServer() {}
func (UnimplementedDiagnosticsServiceServer) testEmbeddedByValue()                            {}

// UnsafeDiagnosticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiagnosticsServiceServer will
// result in compilation errors.
type UnsafeDiagnosticsServiceServer interface {
	mustEmbedUnimplementedDiagnosticsServiceServer()
}

func RegisterDiagnosticsServiceServer(s grpc.ServiceRegistrar, srv DiagnosticsServiceServer) {
	// If the following call pancis, it indicates UnimplementedDiagnosticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiagnosticsService_ServiceDesc, srv)
}

func _DiagnosticsService_RunDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunDiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticsServiceServer).RunDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiagnosticsService_RunDiagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticsServiceServer).RunDiagnostics(ctx, req.(*RunDiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosticsService_GetDiagnosticsResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiagnosticsResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticsServiceServer).GetDiagnosticsResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiagnosticsService_GetDiagnosticsResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticsServiceServer).GetDiagnosticsResult(ctx, req.(*GetDiagnosticsResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosticsService_StreamDiagnostics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamDiagnosticsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DiagnosticsServiceServer).StreamDiagnostics(m, &grpc.GenericServerStream[StreamDiagnosticsRequest, DiagnosticsEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DiagnosticsService_StreamDiagnosticsServer = grpc.ServerStreamingServer[DiagnosticsEvent]

func _DiagnosticsService_ListDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticsServiceServer).ListDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiagnosticsService_ListDiagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticsServiceServer).ListDiagnostics(ctx, req.(*ListDiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiagnosticsService_ServiceDesc is the grpc.ServiceDesc for DiagnosticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiagnosticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lumo.v1.DiagnosticsService",
	HandlerType: (*DiagnosticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunDiagnostics",
			Handler:    _DiagnosticsService_RunDiagnostics_Handler,
		},
		{
			MethodName: "GetDiagnosticsResult",
			Handler:    _DiagnosticsService_GetDiagnosticsResult_Handler,
		},
		{
			MethodName: "ListDiagnostics",
			Handler:    _DiagnosticsService_ListDiagnostics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDiagnostics",
			Handler:       _DiagnosticsService_StreamDiagnostics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/v1/diagnostics.proto",
}
