// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/v1/diagnostics.proto

package lumov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiagnosticsEvent_EventType int32

const (
	DiagnosticsEvent_EVENT_TYPE_UNSPECIFIED     DiagnosticsEvent_EventType = 0
	DiagnosticsEvent_EVENT_TYPE_STARTED         DiagnosticsEvent_EventType = 1
	DiagnosticsEvent_EVENT_TYPE_CHECK_STARTED   DiagnosticsEvent_EventType = 2
	DiagnosticsEvent_EVENT_TYPE_CHECK_COMPLETED DiagnosticsEvent_EventType = 3
	DiagnosticsEvent_EVENT_TYPE_COMPLETED       DiagnosticsEvent_EventType = 4
	DiagnosticsEvent_EVENT_TYPE_FAILED          DiagnosticsEvent_EventType = 5
)

// Enum value maps for DiagnosticsEvent_EventType.
var (
	DiagnosticsEvent_EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_STARTED",
		2: "EVENT_TYPE_CHECK_STARTED",
		3: "EVENT_TYPE_CHECK_COMPLETED",
		4: "EVENT_TYPE_COMPLETED",
		5: "EVENT_TYPE_FAILED",
	}
	DiagnosticsEvent_EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":     0,
		"EVENT_TYPE_STARTED":         1,
		"EVENT_TYPE_CHECK_STARTED":   2,
		"EVENT_TYPE_CHECK_COMPLETED": 3,
		"EVENT_TYPE_COMPLETED":       4,
		"EVENT_TYPE_FAILED":          5,
	}
)

func (x DiagnosticsEvent_EventType) Enum() *DiagnosticsEvent_EventType {
	p := new(DiagnosticsEvent_EventType)
	*p = x
	return p
}

func (x DiagnosticsEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiagnosticsEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_diagnostics_proto_enumTypes[0].Descriptor()
}

func (DiagnosticsEvent_EventType) Type() protoreflect.EnumType {
	return &file_api_proto_v1_diagnostics_proto_enumTypes[0]
}

func (x DiagnosticsEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiagnosticsEvent_EventType.Descriptor instead.
func (DiagnosticsEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_diagnostics_proto_rawDescGZIP(), []int{9, 0}
}

type RunDiagnosticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`                                                                               // Hostname or IP
	Checks        []string               `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"`                                                                               // Empty = all checks
	Analyze       bool                   `protobuf:"varint,3,opt,name=analyze,proto3" json:"analyze,omitempty"`                                                                            // Run AI analysis
	Format        OutputFormat           `protobuf:"varint,4,opt,name=format,proto3,enum=lumo.v1.OutputFormat" json:"format,omitempty"`                                                    // Output format
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional context
	FocusAreas    []string               `protobuf:"bytes,6,rep,name=focus_areas,json=focusAreas,proto3" json:"focus_areas,omitempty"`                                                     // AI focus areas
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunDiagnosticsRequest) Reset() {
	*x = RunDiagnosticsRequest{}
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunDiagnosticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunDiagnosticsRequest) ProtoMessage() {}

func (x *RunDiagnosticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunDiagnosticsRequest.ProtoReflect.Descriptor instead.
func (*RunDiagnosticsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_diagnostics_proto_rawDescGZIP(), []int{0}
}

func (x *RunDiagnosticsRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RunDiagnosticsRequest) GetChecks() []string {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *RunDiagnosticsRequest) GetAnalyze() bool {
	if x != nil {
		return x.Analyze
	}
	return false
}

func (x *RunDiagnosticsRequest) GetFormat() OutputFormat {
	if x != nil {
		return x.Format
	}
	return OutputFormat_OUTPUT_FORMAT_UNSPECIFIED
}

func (x *RunDiagnosticsRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RunDiagnosticsRequest) GetFocusAreas() []string {
	if x != nil {
		return x.FocusAreas
	}
	return nil
}

type RunDiagnosticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // UUID
	Status        JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=lumo.v1.JobStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunDiagnosticsResponse) Reset() {
	*x = RunDiagnosticsResponse{}
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunDiagnosticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunDiagnosticsResponse) ProtoMessage() {}

func (x *RunDiagnosticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunDiagnosticsResponse.ProtoReflect.Descriptor instead.
func (*RunDiagnosticsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_diagnostics_proto_rawDescGZIP(), []int{1}
}

func (x *RunDiagnosticsResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunDiagnosticsResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *RunDiagnosticsResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetDiagnosticsResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiagnosticsResultRequest) Reset() {
	*x = GetDiagnosticsResultRequest{}
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiagnosticsResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiagnosticsResultRequest) ProtoMessage() {}

func (x *GetDiagnosticsResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiagnosticsResultRequest.ProtoReflect.Descriptor instead.
func (*GetDiagnosticsResultRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_diagnostics_proto_rawDescGZIP(), []int{2}
}

func (x *GetDiagnosticsResultRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetDiagnosticsResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=lumo.v1.JobStatus" json:"status,omitempty"`
	Type          JobType                `protobuf:"varint,3,opt,name=type,proto3,enum=lumo.v1.JobType" json:"type,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Result        *DiagnosticsResult     `protobuf:"bytes,8,opt,name=result,proto3" json:"result,omitempty"` // Only present if completed
	Error         string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`   // Only present if failed
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiagnosticsResultResponse) Reset() {
	*x = GetDiagnosticsResultResponse{}
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiagnosticsResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiagnosticsResultResponse) ProtoMessage() {}

func (x *GetDiagnosticsResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiagnosticsResultResponse.ProtoReflect.Descriptor instead.
func (*GetDiagnosticsResultResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_diagnostics_proto_rawDescGZIP(), []int{3}
}

func (x *GetDiagnosticsResultResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetDiagnosticsResultResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *GetDiagnosticsResultResponse) GetType() JobType {
	if x != nil {
		return x.Type
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

func (x *GetDiagnosticsResultResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *GetDiagnosticsResultResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetDiagnosticsResultResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetDiagnosticsResultResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *GetDiagnosticsResultResponse) GetResult() *DiagnosticsResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetDiagnosticsResultResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetDiagnosticsResultResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DiagnosticsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*CheckResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Summary       *ReportSummary         `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Analysis      string                 `protobuf:"bytes,3,opt,name=analysis,proto3" json:"analysis,omitempty"` // AI analysis (if requested)
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DurationMs    int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosticsResult) Reset() {
	*x = DiagnosticsResult{}
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticsResult) ProtoMessage() {}

func (x *DiagnosticsResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticsResult.ProtoReflect.Descriptor instead.
func (*DiagnosticsResult) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_diagnostics_proto_rawDescGZIP(), []int{4}
}

func (x *DiagnosticsResult) GetResults() []*CheckResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *DiagnosticsResult) GetSummary() *ReportSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *DiagnosticsResult) GetAnalysis() string {
	if x != nil {
		return x.Analysis
	}
	return ""
}

func (x *DiagnosticsResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DiagnosticsResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type CheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Status        CheckStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=lumo.v1.CheckStatus" json:"status,omitempty"`
	Severity      Severity               `protobuf:"varint,4,opt,name=severity,proto3,enum=lumo.v1.Severity" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"` // Flexible data (like current map[string]interface{})
	Metrics       []*Metric              `protobuf:"bytes,7,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DurationMs    int64                  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Error         string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResult) Reset() {
	*x = CheckResult{}
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResult) ProtoMessage() {}

func (x *CheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResult.ProtoReflect.Descriptor instead.
func (*CheckResult) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_diagnostics_proto_rawDescGZIP(), []int{5}
}

func (x *CheckResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckResult) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CheckResult) GetStatus() CheckStatus {
	if x != nil {
		return x.Status
	}
	return CheckStatus_CHECK_STATUS_UNSPECIFIED
}

func (x *CheckResult) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *CheckResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckResult) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CheckResult) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *CheckResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CheckResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *CheckResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"` // Numeric metrics
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`     // %, MB, count, etc.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_diagnostics_proto_rawDescGZIP(), []int{6}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Metric) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Metric) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ReportSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalChecks     int32                  `protobuf:"varint,1,opt,name=total_checks,json=totalChecks,proto3" json:"total_checks,omitempty"`
	Passed          int32                  `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	Failed          int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Warnings        int32                  `protobuf:"varint,4,opt,name=warnings,proto3" json:"warnings,omitempty"`
	Skipped         int32                  `protobuf:"varint,5,opt,name=skipped,proto3" json:"skipped,omitempty"`
	OverallSeverity Severity               `protobuf:"varint,6,opt,name=overall_severity,json=overallSeverity,proto3,enum=lumo.v1.Severity" json:"overall_severity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportSummary) Reset() {
	*x = ReportSummary{}
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSummary) ProtoMessage() {}

func (x *ReportSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSummary.ProtoReflect.Descriptor instead.
func (*ReportSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_diagnostics_proto_rawDescGZIP(), []int{7}
}

func (x *ReportSummary) GetTotalChecks() int32 {
	if x != nil {
		return x.TotalChecks
	}
	return 0
}

func (x *ReportSummary) GetPassed() int32 {
	if x != nil {
		return x.Passed
	}
	return 0
}

func (x *ReportSummary) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *ReportSummary) GetWarnings() int32 {
	if x != nil {
		return x.Warnings
	}
	return 0
}

func (x *ReportSummary) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

func (x *ReportSummary) GetOverallSeverity() Severity {
	if x != nil {
		return x.OverallSeverity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

type StreamDiagnosticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Checks        []string               `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"`
	Analyze       bool                   `protobuf:"varint,3,opt,name=analyze,proto3" json:"analyze,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDiagnosticsRequest) Reset() {
	*x = StreamDiagnosticsRequest{}
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDiagnosticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDiagnosticsRequest) ProtoMessage() {}

func (x *StreamDiagnosticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDiagnosticsRequest.ProtoReflect.Descriptor instead.
func (*StreamDiagnosticsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_diagnostics_proto_rawDescGZIP(), []int{8}
}

func (x *StreamDiagnosticsRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *StreamDiagnosticsRequest) GetChecks() []string {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *StreamDiagnosticsRequest) GetAnalyze() bool {
	if x != nil {
		return x.Analyze
	}
	return false
}

type DiagnosticsEvent struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Type          DiagnosticsEvent_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=lumo.v1.DiagnosticsEvent_EventType" json:"type,omitempty"`
	JobId         string                     `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	CheckResult   *CheckResult               `protobuf:"bytes,3,opt,name=check_result,json=checkResult,proto3" json:"check_result,omitempty"` // For CHECK_COMPLETED events
	FinalResult   *DiagnosticsResult         `protobuf:"bytes,4,opt,name=final_result,json=finalResult,proto3" json:"final_result,omitempty"` // For COMPLETED events
	Error         string                     `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                                // For FAILED events
	Progress      int32                      `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`                         // 0-100 percentage
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosticsEvent) Reset() {
	*x = DiagnosticsEvent{}
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticsEvent) ProtoMessage() {}

func (x *DiagnosticsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticsEvent.ProtoReflect.Descriptor instead.
func (*DiagnosticsEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_diagnostics_proto_rawDescGZIP(), []int{9}
}

func (x *DiagnosticsEvent) GetType() DiagnosticsEvent_EventType {
	if x != nil {
		return x.Type
	}
	return DiagnosticsEvent_EVENT_TYPE_UNSPECIFIED
}

func (x *DiagnosticsEvent) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *DiagnosticsEvent) GetCheckResult() *CheckResult {
	if x != nil {
		return x.CheckResult
	}
	return nil
}

func (x *DiagnosticsEvent) GetFinalResult() *DiagnosticsResult {
	if x != nil {
		return x.FinalResult
	}
	return nil
}

func (x *DiagnosticsEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DiagnosticsEvent) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type ListDiagnosticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        JobStatus              `protobuf:"varint,1,opt,name=status,proto3,enum=lumo.v1.JobStatus" json:"status,omitempty"` // Filter by status
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                          // Max results (default 50)
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                        // Pagination offset
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`                         // Filter by target
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDiagnosticsRequest) Reset() {
	*x = ListDiagnosticsRequest{}
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDiagnosticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDiagnosticsRequest) ProtoMessage() {}

func (x *ListDiagnosticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDiagnosticsRequest.ProtoReflect.Descriptor instead.
func (*ListDiagnosticsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_diagnostics_proto_rawDescGZIP(), []int{10}
}

func (x *ListDiagnosticsRequest) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *ListDiagnosticsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDiagnosticsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListDiagnosticsRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type ListDiagnosticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobSummary          `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDiagnosticsResponse) Reset() {
	*x = ListDiagnosticsResponse{}
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDiagnosticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDiagnosticsResponse) ProtoMessage() {}

func (x *ListDiagnosticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDiagnosticsResponse.ProtoReflect.Descriptor instead.
func (*ListDiagnosticsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_diagnostics_proto_rawDescGZIP(), []int{11}
}

func (x *ListDiagnosticsResponse) GetJobs() []*JobSummary {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListDiagnosticsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type JobSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Type          JobType                `protobuf:"varint,2,opt,name=type,proto3,enum=lumo.v1.JobType" json:"type,omitempty"`
	Status        JobStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=lumo.v1.JobStatus" json:"status,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSummary) Reset() {
	*x = JobSummary{}
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSummary) ProtoMessage() {}

func (x *JobSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_diagnostics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSummary.ProtoReflect.Descriptor instead.
func (*JobSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_diagnostics_proto_rawDescGZIP(), []int{12}
}

func (x *JobSummary) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobSummary) GetType() JobType {
	if x != nil {
		return x.Type
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

func (x *JobSummary) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *JobSummary) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *JobSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *JobSummary) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

var File_api_proto_v1_diagnostics_proto protoreflect.FileDescriptor

const file_api_proto_v1_diagnostics_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/v1/diagnostics.proto\x12\alumo.v1\x1a\x19api/proto/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb8\x02\n" +
	"\x15RunDiagnosticsRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x16\n" +
	"\x06checks\x18\x02 \x03(\tR\x06checks\x12\x18\n" +
	"\aanalyze\x18\x03 \x01(\bR\aanalyze\x12-\n" +
	"\x06format\x18\x04 \x01(\x0e2\x15.lumo.v1.OutputFormatR\x06format\x12H\n" +
	"\bmetadata\x18\x05 \x03(\v2,.lumo.v1.RunDiagnosticsRequest.MetadataEntryR\bmetadata\x12\x1f\n" +
	"\vfocus_areas\x18\x06 \x03(\tR\n" +
	"focusAreas\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x01\n" +
	"\x16RunDiagnosticsResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.lumo.v1.JobStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"4\n" +
	"\x1bGetDiagnosticsResultRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xac\x04\n" +
	"\x1cGetDiagnosticsResultResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.lumo.v1.JobStatusR\x06status\x12$\n" +
	"\x04type\x18\x03 \x01(\x0e2\x10.lumo.v1.JobTypeR\x04type\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x122\n" +
	"\x06result\x18\b \x01(\v2\x1a.lumo.v1.DiagnosticsResultR\x06result\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x12O\n" +
	"\bmetadata\x18\n" +
	" \x03(\v23.lumo.v1.GetDiagnosticsResultResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xec\x01\n" +
	"\x11DiagnosticsResult\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.lumo.v1.CheckResultR\aresults\x120\n" +
	"\asummary\x18\x02 \x01(\v2\x16.lumo.v1.ReportSummaryR\asummary\x12\x1a\n" +
	"\banalysis\x18\x03 \x01(\tR\banalysis\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\"\xfd\x02\n" +
	"\vCheckResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12,\n" +
	"\x06status\x18\x03 \x01(\x0e2\x14.lumo.v1.CheckStatusR\x06status\x12-\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x11.lumo.v1.SeverityR\bseverity\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04data\x12)\n" +
	"\ametrics\x18\a \x03(\v2\x0f.lumo.v1.MetricR\ametrics\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\"\xf0\x01\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x123\n" +
	"\x06labels\x18\x05 \x03(\v2\x1b.lumo.v1.Metric.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd6\x01\n" +
	"\rReportSummary\x12!\n" +
	"\ftotal_checks\x18\x01 \x01(\x05R\vtotalChecks\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\x05R\x06passed\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x12\x1a\n" +
	"\bwarnings\x18\x04 \x01(\x05R\bwarnings\x12\x18\n" +
	"\askipped\x18\x05 \x01(\x05R\askipped\x12<\n" +
	"\x10overall_severity\x18\x06 \x01(\x0e2\x11.lumo.v1.SeverityR\x0foverallSeverity\"d\n" +
	"\x18StreamDiagnosticsRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x16\n" +
	"\x06checks\x18\x02 \x03(\tR\x06checks\x12\x18\n" +
	"\aanalyze\x18\x03 \x01(\bR\aanalyze\"\xbd\x03\n" +
	"\x10DiagnosticsEvent\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.lumo.v1.DiagnosticsEvent.EventTypeR\x04type\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x127\n" +
	"\fcheck_result\x18\x03 \x01(\v2\x14.lumo.v1.CheckResultR\vcheckResult\x12=\n" +
	"\ffinal_result\x18\x04 \x01(\v2\x1a.lumo.v1.DiagnosticsResultR\vfinalResult\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x05R\bprogress\"\xae\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_TYPE_STARTED\x10\x01\x12\x1c\n" +
	"\x18EVENT_TYPE_CHECK_STARTED\x10\x02\x12\x1e\n" +
	"\x1aEVENT_TYPE_CHECK_COMPLETED\x10\x03\x12\x18\n" +
	"\x14EVENT_TYPE_COMPLETED\x10\x04\x12\x15\n" +
	"\x11EVENT_TYPE_FAILED\x10\x05\"\x8a\x01\n" +
	"\x16ListDiagnosticsRequest\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.lumo.v1.JobStatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\"c\n" +
	"\x17ListDiagnosticsResponse\x12'\n" +
	"\x04jobs\x18\x01 \x03(\v2\x13.lumo.v1.JobSummaryR\x04jobs\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x87\x02\n" +
	"\n" +
	"JobSummary\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12$\n" +
	"\x04type\x18\x02 \x01(\x0e2\x10.lumo.v1.JobTypeR\x04type\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.lumo.v1.JobStatusR\x06status\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt2\xf7\x02\n" +
	"\x12DiagnosticsService\x12Q\n" +
	"\x0eRunDiagnostics\x12\x1e.lumo.v1.RunDiagnosticsRequest\x1a\x1f.lumo.v1.RunDiagnosticsResponse\x12c\n" +
	"\x14GetDiagnosticsResult\x12$.lumo.v1.GetDiagnosticsResultRequest\x1a%.lumo.v1.GetDiagnosticsResultResponse\x12S\n" +
	"\x11StreamDiagnostics\x12!.lumo.v1.StreamDiagnosticsRequest\x1a\x19.lumo.v1.DiagnosticsEvent0\x01\x12T\n" +
	"\x0fListDiagnostics\x12\x1f.lumo.v1.ListDiagnosticsRequest\x1a .lumo.v1.ListDiagnosticsResponseB-Z+github.com/ignacio/lumo/api/proto/v1;lumov1b\x06proto3"

var (
	file_api_proto_v1_diagnostics_proto_rawDescOnce sync.Once
	file_api_proto_v1_diagnostics_proto_rawDescData []byte
)

func file_api_proto_v1_diagnostics_proto_rawDescGZIP() []byte {
	file_api_proto_v1_diagnostics_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_diagnostics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_diagnostics_proto_rawDesc), len(file_api_proto_v1_diagnostics_proto_rawDesc)))
	})
	return file_api_proto_v1_diagnostics_proto_rawDescData
}

var file_api_proto_v1_diagnostics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_diagnostics_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_proto_v1_diagnostics_proto_goTypes = []any{
	(DiagnosticsEvent_EventType)(0),      // 0: lumo.v1.DiagnosticsEvent.EventType
	(*RunDiagnosticsRequest)(nil),        // 1: lumo.v1.RunDiagnosticsRequest
	(*RunDiagnosticsResponse)(nil),       // 2: lumo.v1.RunDiagnosticsResponse
	(*GetDiagnosticsResultRequest)(nil),  // 3: lumo.v1.GetDiagnosticsResultRequest
	(*GetDiagnosticsResultResponse)(nil), // 4: lumo.v1.GetDiagnosticsResultResponse
	(*DiagnosticsResult)(nil),            // 5: lumo.v1.DiagnosticsResult
	(*CheckResult)(nil),                  // 6: lumo.v1.CheckResult
	(*Metric)(nil),                       // 7: lumo.v1.Metric
	(*ReportSummary)(nil),                // 8: lumo.v1.ReportSummary
	(*StreamDiagnosticsRequest)(nil),     // 9: lumo.v1.StreamDiagnosticsRequest
	(*DiagnosticsEvent)(nil),             // 10: lumo.v1.DiagnosticsEvent
	(*ListDiagnosticsRequest)(nil),       // 11: lumo.v1.ListDiagnosticsRequest
	(*ListDiagnosticsResponse)(nil),      // 12: lumo.v1.ListDiagnosticsResponse
	(*JobSummary)(nil),                   // 13: lumo.v1.JobSummary
	nil,                                  // 14: lumo.v1.RunDiagnosticsRequest.MetadataEntry
	nil,                                  // 15: lumo.v1.GetDiagnosticsResultResponse.MetadataEntry
	nil,                                  // 16: lumo.v1.Metric.LabelsEntry
	(OutputFormat)(0),                    // 17: lumo.v1.OutputFormat
	(JobStatus)(0),                       // 18: lumo.v1.JobStatus
	(*timestamppb.Timestamp)(nil),        // 19: google.protobuf.Timestamp
	(JobType)(0),                         // 20: lumo.v1.JobType
	(CheckStatus)(0),                     // 21: lumo.v1.CheckStatus
	(Severity)(0),                        // 22: lumo.v1.Severity
	(*structpb.Struct)(nil),              // 23: google.protobuf.Struct
}
var file_api_proto_v1_diagnostics_proto_depIdxs = []int32{
	17, // 0: lumo.v1.RunDiagnosticsRequest.format:type_name -> lumo.v1.OutputFormat
	14, // 1: lumo.v1.RunDiagnosticsRequest.metadata:type_name -> lumo.v1.RunDiagnosticsRequest.MetadataEntry
	18, // 2: lumo.v1.RunDiagnosticsResponse.status:type_name -> lumo.v1.JobStatus
	19, // 3: lumo.v1.RunDiagnosticsResponse.created_at:type_name -> google.protobuf.Timestamp
	18, // 4: lumo.v1.GetDiagnosticsResultResponse.status:type_name -> lumo.v1.JobStatus
	20, // 5: lumo.v1.GetDiagnosticsResultResponse.type:type_name -> lumo.v1.JobType
	19, // 6: lumo.v1.GetDiagnosticsResultResponse.created_at:type_name -> google.protobuf.Timestamp
	19, // 7: lumo.v1.GetDiagnosticsResultResponse.started_at:type_name -> google.protobuf.Timestamp
	19, // 8: lumo.v1.GetDiagnosticsResultResponse.completed_at:type_name -> google.protobuf.Timestamp
	5,  // 9: lumo.v1.GetDiagnosticsResultResponse.result:type_name -> lumo.v1.DiagnosticsResult
	15, // 10: lumo.v1.GetDiagnosticsResultResponse.metadata:type_name -> lumo.v1.GetDiagnosticsResultResponse.MetadataEntry
	6,  // 11: lumo.v1.DiagnosticsResult.results:type_name -> lumo.v1.CheckResult
	8,  // 12: lumo.v1.DiagnosticsResult.summary:type_name -> lumo.v1.ReportSummary
	19, // 13: lumo.v1.DiagnosticsResult.timestamp:type_name -> google.protobuf.Timestamp
	21, // 14: lumo.v1.CheckResult.status:type_name -> lumo.v1.CheckStatus
	22, // 15: lumo.v1.CheckResult.severity:type_name -> lumo.v1.Severity
	23, // 16: lumo.v1.CheckResult.data:type_name -> google.protobuf.Struct
	7,  // 17: lumo.v1.CheckResult.metrics:type_name -> lumo.v1.Metric
	19, // 18: lumo.v1.CheckResult.timestamp:type_name -> google.protobuf.Timestamp
	19, // 19: lumo.v1.Metric.timestamp:type_name -> google.protobuf.Timestamp
	16, // 20: lumo.v1.Metric.labels:type_name -> lumo.v1.Metric.LabelsEntry
	22, // 21: lumo.v1.ReportSummary.overall_severity:type_name -> lumo.v1.Severity
	0,  // 22: lumo.v1.DiagnosticsEvent.type:type_name -> lumo.v1.DiagnosticsEvent.EventType
	6,  // 23: lumo.v1.DiagnosticsEvent.check_result:type_name -> lumo.v1.CheckResult
	5,  // 24: lumo.v1.DiagnosticsEvent.final_result:type_name -> lumo.v1.DiagnosticsResult
	18, // 25: lumo.v1.ListDiagnosticsRequest.status:type_name -> lumo.v1.JobStatus
	13, // 26: lumo.v1.ListDiagnosticsResponse.jobs:type_name -> lumo.v1.JobSummary
	20, // 27: lumo.v1.JobSummary.type:type_name -> lumo.v1.JobType
	18, // 28: lumo.v1.JobSummary.status:type_name -> lumo.v1.JobStatus
	19, // 29: lumo.v1.JobSummary.created_at:type_name -> google.protobuf.Timestamp
	19, // 30: lumo.v1.JobSummary.completed_at:type_name -> google.protobuf.Timestamp
	1,  // 31: lumo.v1.DiagnosticsService.RunDiagnostics:input_type -> lumo.v1.RunDiagnosticsRequest
	3,  // 32: lumo.v1.DiagnosticsService.GetDiagnosticsResult:input_type -> lumo.v1.GetDiagnosticsResultRequest
	9,  // 33: lumo.v1.DiagnosticsService.StreamDiagnostics:input_type -> lumo.v1.StreamDiagnosticsRequest
	11, // 34: lumo.v1.DiagnosticsService.ListDiagnostics:input_type -> lumo.v1.ListDiagnosticsRequest
	2,  // 35: lumo.v1.DiagnosticsService.RunDiagnostics:output_type -> lumo.v1.RunDiagnosticsResponse
	4,  // 36: lumo.v1.DiagnosticsService.GetDiagnosticsResult:output_type -> lumo.v1.GetDiagnosticsResultResponse
	10, // 37: lumo.v1.DiagnosticsService.StreamDiagnostics:output_type -> lumo.v1.DiagnosticsEvent
	12, // 38: lumo.v1.DiagnosticsService.ListDiagnostics:output_type -> lumo.v1.ListDiagnosticsResponse
	35, // [35:39] is the sub-list for method output_type
	31, // [31:35] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_api_proto_v1_diagnostics_proto_init() }
func file_api_proto_v1_diagnostics_proto_init() {
	if File_api_proto_v1_diagnostics_proto != nil {
		return
	}
	file_api_proto_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_diagnostics_proto_rawDesc), len(file_api_proto_v1_diagnostics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_diagnostics_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_diagnostics_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_diagnostics_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_diagnostics_proto_msgTypes,
	}.Build()
	File_api_proto_v1_diagnostics_proto = out.File
	file_api_proto_v1_diagnostics_proto_goTypes = nil
	file_api_proto_v1_diagnostics_proto_depIdxs = nil
}
