// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/v1/health.proto

package lumov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_SERVING_STATUS_UNSPECIFIED HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING_STATUS_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_SERVING_STATUS_NOT_SERVING HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVING_STATUS_UNKNOWN     HealthCheckResponse_ServingStatus = 3
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "SERVING_STATUS_UNSPECIFIED",
		1: "SERVING_STATUS_SERVING",
		2: "SERVING_STATUS_NOT_SERVING",
		3: "SERVING_STATUS_UNKNOWN",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"SERVING_STATUS_UNSPECIFIED": 0,
		"SERVING_STATUS_SERVING":     1,
		"SERVING_STATUS_NOT_SERVING": 2,
		"SERVING_STATUS_UNKNOWN":     3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_health_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_api_proto_v1_health_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_health_proto_rawDescGZIP(), []int{1, 0}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"` // Optional: check specific service
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=lumo.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Version       string                            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Uptime        *timestamppb.Timestamp            `protobuf:"bytes,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Components    map[string]*ComponentHealth       `protobuf:"bytes,4,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_SERVING_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptime() *timestamppb.Timestamp {
	if x != nil {
		return x.Uptime
	}
	return nil
}

func (x *HealthCheckResponse) GetComponents() map[string]*ComponentHealth {
	if x != nil {
		return x.Components
	}
	return nil
}

type ComponentHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentHealth) Reset() {
	*x = ComponentHealth{}
	mi := &file_api_proto_v1_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentHealth) ProtoMessage() {}

func (x *ComponentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentHealth.ProtoReflect.Descriptor instead.
func (*ComponentHealth) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_health_proto_rawDescGZIP(), []int{2}
}

func (x *ComponentHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ComponentHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_api_proto_v1_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_health_proto_rawDescGZIP(), []int{3}
}

type ReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_api_proto_v1_health_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_health_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_health_proto_rawDescGZIP(), []int{4}
}

func (x *ReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ReadyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveRequest) Reset() {
	*x = LiveRequest{}
	mi := &file_api_proto_v1_health_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveRequest) ProtoMessage() {}

func (x *LiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_health_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveRequest.ProtoReflect.Descriptor instead.
func (*LiveRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_health_proto_rawDescGZIP(), []int{5}
}

type LiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveResponse) Reset() {
	*x = LiveResponse{}
	mi := &file_api_proto_v1_health_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveResponse) ProtoMessage() {}

func (x *LiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_health_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveResponse.ProtoReflect.Descriptor instead.
func (*LiveResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_health_proto_rawDescGZIP(), []int{6}
}

func (x *LiveResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *LiveResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_api_proto_v1_health_proto protoreflect.FileDescriptor

const file_api_proto_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/v1/health.proto\x12\alumo.v1\x1a\x1fgoogle/protobuf/timestamp.proto\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xd8\x03\n" +
	"\x13HealthCheckResponse\x12B\n" +
	"\x06status\x18\x01 \x01(\x0e2*.lumo.v1.HealthCheckResponse.ServingStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x122\n" +
	"\x06uptime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06uptime\x12L\n" +
	"\n" +
	"components\x18\x04 \x03(\v2,.lumo.v1.HealthCheckResponse.ComponentsEntryR\n" +
	"components\x1aW\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.lumo.v1.ComponentHealthR\x05value:\x028\x01\"\x87\x01\n" +
	"\rServingStatus\x12\x1e\n" +
	"\x1aSERVING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SERVING_STATUS_SERVING\x10\x01\x12\x1e\n" +
	"\x1aSERVING_STATUS_NOT_SERVING\x10\x02\x12\x1a\n" +
	"\x16SERVING_STATUS_UNKNOWN\x10\x03\"E\n" +
	"\x0fComponentHealth\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0e\n" +
	"\fReadyRequest\"?\n" +
	"\rReadyResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\r\n" +
	"\vLiveRequest\"^\n" +
	"\fLiveResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\xc0\x01\n" +
	"\rHealthService\x12B\n" +
	"\x05Check\x12\x1b.lumo.v1.HealthCheckRequest\x1a\x1c.lumo.v1.HealthCheckResponse\x126\n" +
	"\x05Ready\x12\x15.lumo.v1.ReadyRequest\x1a\x16.lumo.v1.ReadyResponse\x123\n" +
	"\x04Live\x12\x14.lumo.v1.LiveRequest\x1a\x15.lumo.v1.LiveResponseB-Z+github.com/ignacio/lumo/api/proto/v1;lumov1b\x06proto3"

var (
	file_api_proto_v1_health_proto_rawDescOnce sync.Once
	file_api_proto_v1_health_proto_rawDescData []byte
)

func file_api_proto_v1_health_proto_rawDescGZIP() []byte {
	file_api_proto_v1_health_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_health_proto_rawDesc), len(file_api_proto_v1_health_proto_rawDesc)))
	})
	return file_api_proto_v1_health_proto_rawDescData
}

var file_api_proto_v1_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_v1_health_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: lumo.v1.HealthCheckResponse.ServingStatus
	(*HealthCheckRequest)(nil),             // 1: lumo.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 2: lumo.v1.HealthCheckResponse
	(*ComponentHealth)(nil),                // 3: lumo.v1.ComponentHealth
	(*ReadyRequest)(nil),                   // 4: lumo.v1.ReadyRequest
	(*ReadyResponse)(nil),                  // 5: lumo.v1.ReadyResponse
	(*LiveRequest)(nil),                    // 6: lumo.v1.LiveRequest
	(*LiveResponse)(nil),                   // 7: lumo.v1.LiveResponse
	nil,                                    // 8: lumo.v1.HealthCheckResponse.ComponentsEntry
	(*timestamppb.Timestamp)(nil),          // 9: google.protobuf.Timestamp
}
var file_api_proto_v1_health_proto_depIdxs = []int32{
	0, // 0: lumo.v1.HealthCheckResponse.status:type_name -> lumo.v1.HealthCheckResponse.ServingStatus
	9, // 1: lumo.v1.HealthCheckResponse.uptime:type_name -> google.protobuf.Timestamp
	8, // 2: lumo.v1.HealthCheckResponse.components:type_name -> lumo.v1.HealthCheckResponse.ComponentsEntry
	9, // 3: lumo.v1.LiveResponse.timestamp:type_name -> google.protobuf.Timestamp
	3, // 4: lumo.v1.HealthCheckResponse.ComponentsEntry.value:type_name -> lumo.v1.ComponentHealth
	1, // 5: lumo.v1.HealthService.Check:input_type -> lumo.v1.HealthCheckRequest
	4, // 6: lumo.v1.HealthService.Ready:input_type -> lumo.v1.ReadyRequest
	6, // 7: lumo.v1.HealthService.Live:input_type -> lumo.v1.LiveRequest
	2, // 8: lumo.v1.HealthService.Check:output_type -> lumo.v1.HealthCheckResponse
	5, // 9: lumo.v1.HealthService.Ready:output_type -> lumo.v1.ReadyResponse
	7, // 10: lumo.v1.HealthService.Live:output_type -> lumo.v1.LiveResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_v1_health_proto_init() }
func file_api_proto_v1_health_proto_init() {
	if File_api_proto_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_health_proto_rawDesc), len(file_api_proto_v1_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_health_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_health_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_health_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_health_proto_msgTypes,
	}.Build()
	File_api_proto_v1_health_proto = out.File
	file_api_proto_v1_health_proto_goTypes = nil
	file_api_proto_v1_health_proto_depIdxs = nil
}
