package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"text/tabwriter"
	"time"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/ignacio/lumo/internal/config"
	"github.com/ignacio/lumo/internal/database"
	"github.com/ignacio/lumo/internal/database/models"
	"github.com/ignacio/lumo/internal/database/repository"
)

var eventsCmd = &cobra.Command{
	Use:   "events",
	Short: "Query events from the database",
	Long: `Query Kubernetes events stored in the PostgreSQL database.

This command provides a native way to query events without needing kubectl
or psql access. Events are generated by agents monitoring Kubernetes clusters
and include pod failures, deployments, volume issues, and more.

Examples:
  lumo events                                    # Show last 20 events
  lumo events --limit 50                         # Show last 50 events
  lumo events --severity critical                # Show only critical events
  lumo events --severity high,critical           # Show high and critical events
  lumo events --type oom-killed                  # Show only OOMKilled events
  lumo events --namespace kube-system            # Show events from specific namespace
  lumo events --since 24h                        # Show events from last 24 hours
  lumo events --format json                      # Output as JSON
  lumo events --format yaml                      # Output as YAML
  lumo events --no-analysis                      # Hide AI analysis column`,
	Run: func(cmd *cobra.Command, args []string) {
		if err := runEvents(cmd, args); err != nil {
			log.Errorf("Failed to query events: %v", err)
			os.Exit(1)
		}
	},
}

func init() {
	rootCmd.AddCommand(eventsCmd)

	// Query filters
	eventsCmd.Flags().IntP("limit", "l", 20, "Maximum number of events to return")
	eventsCmd.Flags().StringP("severity", "s", "", "Filter by severity (low, medium, high, critical) - comma-separated for multiple")
	eventsCmd.Flags().StringP("type", "t", "", "Filter by event type (e.g., oom-killed, crash-loop-backoff)")
	eventsCmd.Flags().StringP("namespace", "n", "", "Filter by Kubernetes namespace")
	eventsCmd.Flags().StringP("resource", "r", "", "Filter by resource kind (e.g., Pod, Deployment)")
	eventsCmd.Flags().String("since", "", "Show events since duration (e.g., 24h, 7d)")

	// Output options
	eventsCmd.Flags().StringP("format", "f", "table", "Output format (table, json, yaml)")
	eventsCmd.Flags().Bool("no-analysis", false, "Hide AI analysis column in table output")
	eventsCmd.Flags().Bool("show-metadata", false, "Show event metadata in table output")
}

func runEvents(cmd *cobra.Command, args []string) error {
	ctx := context.Background()

	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		return fmt.Errorf("failed to load config: %w", err)
	}

	// Connect to database
	log.Info("Connecting to database...")
	dbConfig := &database.PostgresConfig{
		Host:            cfg.Database.Host,
		Port:            cfg.Database.Port,
		Name:            cfg.Database.Name,
		User:            cfg.Database.User,
		Password:        cfg.Database.Password,
		SSLMode:         cfg.Database.SSLMode,
		MaxConnections:  cfg.Database.MaxConnections,
		MaxIdle:         cfg.Database.MaxIdle,
		ConnMaxLifetime: cfg.Database.ConnMaxLifetime,
	}

	db, err := database.NewPostgresDB(dbConfig, log)
	if err != nil {
		return fmt.Errorf("failed to connect to database: %w", err)
	}
	defer func() {
		if err := db.Close(); err != nil {
			log.Warnf("Failed to close database: %v", err)
		}
	}()

	// Create repository
	eventRepo := repository.NewEventRepository(db.DB)

	// Parse flags and build filters
	filters := make(map[string]interface{})

	// Limit
	limit, _ := cmd.Flags().GetInt("limit")
	if limit > 0 {
		filters["limit"] = limit
	}

	// Severity filter
	if severityStr, _ := cmd.Flags().GetString("severity"); severityStr != "" {
		// Support multiple severities comma-separated
		severities := strings.Split(severityStr, ",")
		if len(severities) == 1 {
			// Single severity
			severity := models.EventSeverity(strings.TrimSpace(severities[0]))
			if !isValidSeverity(severity) {
				return fmt.Errorf("invalid severity: %s (must be: low, medium, high, critical)", severity)
			}
			filters["severity"] = severity
		} else {
			// Multiple severities - we'll need to query multiple times and combine
			// For now, use the first one and log a warning
			log.Warn("Multiple severity filtering not yet supported, using first severity only")
			severity := models.EventSeverity(strings.TrimSpace(severities[0]))
			if !isValidSeverity(severity) {
				return fmt.Errorf("invalid severity: %s (must be: low, medium, high, critical)", severity)
			}
			filters["severity"] = severity
		}
	}

	// Event type filter
	if eventType, _ := cmd.Flags().GetString("type"); eventType != "" {
		filters["event_type"] = eventType
	}

	// Namespace filter
	if namespace, _ := cmd.Flags().GetString("namespace"); namespace != "" {
		filters["namespace"] = namespace
	}

	// Resource kind filter
	if resourceKind, _ := cmd.Flags().GetString("resource"); resourceKind != "" {
		filters["resource_kind"] = resourceKind
	}

	// Time range filter
	if sinceStr, _ := cmd.Flags().GetString("since"); sinceStr != "" {
		duration, err := parseDuration(sinceStr)
		if err != nil {
			return fmt.Errorf("invalid duration: %w", err)
		}
		filters["since"] = time.Now().Add(-duration)
	}

	// Sort by event_timestamp descending
	filters["sort"] = "event_timestamp"

	// Query events
	log.Info("Querying events...")
	events, err := eventRepo.List(ctx, filters)
	if err != nil {
		return fmt.Errorf("failed to query events: %w", err)
	}

	if len(events) == 0 {
		log.Info("No events found matching the specified filters")
		return nil
	}

	// Output based on format
	format, _ := cmd.Flags().GetString("format")
	noAnalysis, _ := cmd.Flags().GetBool("no-analysis")
	showMetadata, _ := cmd.Flags().GetBool("show-metadata")

	switch format {
	case "json":
		return outputJSON(events)
	case "yaml":
		return outputYAML(events)
	case "table":
		return outputTable(events, noAnalysis, showMetadata)
	default:
		return fmt.Errorf("unsupported format: %s (must be: table, json, yaml)", format)
	}
}

func outputTable(events []*models.Event, noAnalysis, showMetadata bool) error {
	w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
	defer func() {
		_ = w.Flush()
	}()

	// Header
	if noAnalysis && !showMetadata {
		_, _ = fmt.Fprintln(w, "EVENT TYPE\tSEVERITY\tRESOURCE\tNAMESPACE\tTIMESTAMP")
	} else if noAnalysis && showMetadata {
		_, _ = fmt.Fprintln(w, "EVENT TYPE\tSEVERITY\tRESOURCE\tNAMESPACE\tMETADATA\tTIMESTAMP")
	} else if !noAnalysis && showMetadata {
		_, _ = fmt.Fprintln(w, "EVENT TYPE\tSEVERITY\tRESOURCE\tNAMESPACE\tMETADATA\tAI ANALYSIS\tTIMESTAMP")
	} else {
		_, _ = fmt.Fprintln(w, "EVENT TYPE\tSEVERITY\tRESOURCE\tNAMESPACE\tAI ANALYSIS\tTIMESTAMP")
	}

	// Rows
	for _, event := range events {
		// Format resource name
		resource := fmt.Sprintf("%s/%s", event.ResourceKind, event.ResourceName)

		// Format namespace
		namespace := "-"
		if event.Namespace != nil && *event.Namespace != "" {
			namespace = *event.Namespace
		}

		// Format timestamp
		timestamp := event.EventTimestamp.Format("2006-01-02 15:04:05")

		// Format AI analysis status
		aiStatus := "No"
		if event.HasAIAnalysis() {
			aiStatus = "Yes"
		}

		// Format metadata
		metadata := "-"
		if showMetadata && event.Metadata != nil {
			metaJSON, err := json.Marshal(event.Metadata)
			if err == nil {
				// Truncate if too long
				metaStr := string(metaJSON)
				if len(metaStr) > 40 {
					metaStr = metaStr[:37] + "..."
				}
				metadata = metaStr
			}
		}

		// Print row based on column selection
		if noAnalysis && !showMetadata {
			_, _ = fmt.Fprintf(w, "%s\t%s\t%s\t%s\t%s\n",
				event.EventType,
				event.Severity,
				resource,
				namespace,
				timestamp,
			)
		} else if noAnalysis && showMetadata {
			_, _ = fmt.Fprintf(w, "%s\t%s\t%s\t%s\t%s\t%s\n",
				event.EventType,
				event.Severity,
				resource,
				namespace,
				metadata,
				timestamp,
			)
		} else if !noAnalysis && showMetadata {
			_, _ = fmt.Fprintf(w, "%s\t%s\t%s\t%s\t%s\t%s\t%s\n",
				event.EventType,
				event.Severity,
				resource,
				namespace,
				metadata,
				aiStatus,
				timestamp,
			)
		} else {
			_, _ = fmt.Fprintf(w, "%s\t%s\t%s\t%s\t%s\t%s\n",
				event.EventType,
				event.Severity,
				resource,
				namespace,
				aiStatus,
				timestamp,
			)
		}
	}

	// Summary
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintf(w, "Total events: %d\n", len(events))

	return nil
}

func outputJSON(events []*models.Event) error {
	encoder := json.NewEncoder(os.Stdout)
	encoder.SetIndent("", "  ")
	return encoder.Encode(events)
}

func outputYAML(events []*models.Event) error {
	data, err := yaml.Marshal(events)
	if err != nil {
		return fmt.Errorf("failed to marshal YAML: %w", err)
	}
	fmt.Println(string(data))
	return nil
}

func isValidSeverity(severity models.EventSeverity) bool {
	switch severity {
	case models.EventSeverityLow, models.EventSeverityMedium,
		models.EventSeverityHigh, models.EventSeverityCritical:
		return true
	default:
		return false
	}
}

func parseDuration(s string) (time.Duration, error) {
	// Support common suffixes like "24h", "7d", "30m"
	if strings.HasSuffix(s, "d") {
		// Parse days
		days := strings.TrimSuffix(s, "d")
		var d int
		_, err := fmt.Sscanf(days, "%d", &d)
		if err != nil {
			return 0, err
		}
		return time.Duration(d) * 24 * time.Hour, nil
	}

	// Otherwise use standard time.ParseDuration
	return time.ParseDuration(s)
}
