package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"text/tabwriter"
	"time"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/ignacio/lumo/internal/config"
	"github.com/ignacio/lumo/internal/database"
	"github.com/ignacio/lumo/internal/database/models"
	"github.com/ignacio/lumo/internal/database/repository"
)

const (
	// MaxEventLimit prevents DoS via excessive result sets
	MaxEventLimit = 10000
	// DefaultEventLimit is the default number of events to return
	DefaultEventLimit = 20
)

var eventsCmd = &cobra.Command{
	Use:   "events",
	Short: "Query events from the database",
	Long: `Query Kubernetes events stored in the PostgreSQL database.

This command provides a native way to query events without needing kubectl
or psql access. Events are generated by agents monitoring Kubernetes clusters
and include pod failures, deployments, volume issues, and more.

Examples:
  lumo events                                    # Show last 20 events
  lumo events --limit 50                         # Show last 50 events
  lumo events --severity critical                # Show only critical events
  lumo events --severity high,critical           # Show high and critical events
  lumo events --type oom-killed                  # Show only OOMKilled events
  lumo events --namespace kube-system            # Show events from specific namespace
  lumo events --since 24h                        # Show events from last 24 hours
  lumo events --format json                      # Output as JSON
  lumo events --format yaml                      # Output as YAML
  lumo events --no-analysis                      # Hide AI analysis column`,
	Run: func(cmd *cobra.Command, args []string) {
		if err := runEvents(cmd, args); err != nil {
			log.Errorf("Failed to query events: %v", err)
			os.Exit(1)
		}
	},
}

func init() {
	rootCmd.AddCommand(eventsCmd)

	// Query filters
	eventsCmd.Flags().IntP("limit", "l", DefaultEventLimit, "Maximum number of events to return (max: 10000)")
	eventsCmd.Flags().StringP("severity", "s", "", "Filter by severity (low, medium, high, critical) - comma-separated for multiple")
	eventsCmd.Flags().StringP("type", "t", "", "Filter by event type (e.g., oom-killed, crash-loop-backoff)")
	eventsCmd.Flags().StringP("namespace", "n", "", "Filter by Kubernetes namespace")
	eventsCmd.Flags().StringP("resource", "r", "", "Filter by resource kind (e.g., Pod, Deployment)")
	eventsCmd.Flags().String("since", "", "Show events since duration (e.g., 24h, 7d)")

	// Output options
	eventsCmd.Flags().StringP("format", "f", "table", "Output format (table, json, yaml)")
	eventsCmd.Flags().Bool("no-analysis", false, "Hide AI analysis column in table output")
	eventsCmd.Flags().Bool("show-metadata", false, "Show event metadata in table output")
}

func runEvents(cmd *cobra.Command, args []string) error {
	ctx := context.Background()

	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		return fmt.Errorf("failed to load config: %w", err)
	}

	// Connect to database
	log.Info("Connecting to database...")
	dbConfig := &database.PostgresConfig{
		Host:            cfg.Database.Host,
		Port:            cfg.Database.Port,
		Name:            cfg.Database.Name,
		User:            cfg.Database.User,
		Password:        cfg.Database.Password,
		SSLMode:         cfg.Database.SSLMode,
		MaxConnections:  cfg.Database.MaxConnections,
		MaxIdle:         cfg.Database.MaxIdle,
		ConnMaxLifetime: cfg.Database.ConnMaxLifetime,
	}

	db, err := database.NewPostgresDB(dbConfig, log)
	if err != nil {
		return fmt.Errorf("failed to connect to database: %w", err)
	}
	defer func() {
		if err := db.Close(); err != nil {
			log.Warnf("Failed to close database: %v", err)
		}
	}()

	// Create repository
	eventRepo := repository.NewEventRepository(db.DB)

	// Parse flags and build filters
	filters := make(map[string]interface{})

	// Limit with bounds validation
	limit, _ := cmd.Flags().GetInt("limit")
	if limit <= 0 {
		limit = DefaultEventLimit
	}
	if limit > MaxEventLimit {
		log.Warnf("Limit %d exceeds maximum (%d), using maximum", limit, MaxEventLimit)
		limit = MaxEventLimit
	}
	filters["limit"] = limit

	// Severity filter (supports multiple comma-separated values)
	if severityStr, _ := cmd.Flags().GetString("severity"); severityStr != "" {
		severities := strings.Split(severityStr, ",")
		validSeverities := make([]models.EventSeverity, 0, len(severities))
		for _, s := range severities {
			severity := models.EventSeverity(strings.TrimSpace(s))
			if !isValidSeverity(severity) {
				return fmt.Errorf("invalid severity: %s (must be: low, medium, high, critical)", severity)
			}
			validSeverities = append(validSeverities, severity)
		}
		if len(validSeverities) == 1 {
			filters["severity"] = validSeverities[0]
		} else {
			filters["severities"] = validSeverities
		}
	}

	// Event type filter
	if eventType, _ := cmd.Flags().GetString("type"); eventType != "" {
		filters["event_type"] = eventType
	}

	// Namespace filter
	if namespace, _ := cmd.Flags().GetString("namespace"); namespace != "" {
		filters["namespace"] = namespace
	}

	// Resource kind filter
	if resourceKind, _ := cmd.Flags().GetString("resource"); resourceKind != "" {
		filters["resource_kind"] = resourceKind
	}

	// Time range filter
	if sinceStr, _ := cmd.Flags().GetString("since"); sinceStr != "" {
		duration, err := parseDuration(sinceStr)
		if err != nil {
			return fmt.Errorf("invalid duration: %w", err)
		}
		filters["since"] = time.Now().Add(-duration)
	}

	// Sort by event_timestamp descending
	filters["sort"] = "event_timestamp"

	// Query events
	log.Info("Querying events...")
	events, err := eventRepo.List(ctx, filters)
	if err != nil {
		return fmt.Errorf("failed to query events: %w", err)
	}

	if len(events) == 0 {
		log.Info("No events found matching the specified filters")
		return nil
	}

	// Output based on format
	format, _ := cmd.Flags().GetString("format")
	noAnalysis, _ := cmd.Flags().GetBool("no-analysis")
	showMetadata, _ := cmd.Flags().GetBool("show-metadata")

	switch format {
	case "json":
		return outputJSON(events)
	case "yaml":
		return outputYAML(events)
	case "table":
		return outputTable(events, noAnalysis, showMetadata)
	default:
		return fmt.Errorf("unsupported format: %s (must be: table, json, yaml)", format)
	}
}

func outputTable(events []*models.Event, noAnalysis, showMetadata bool) error {
	w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
	defer func() {
		_ = w.Flush()
	}()

	// Build columns dynamically based on options
	columns := []string{"EVENT TYPE", "SEVERITY", "RESOURCE", "NAMESPACE"}
	if showMetadata {
		columns = append(columns, "METADATA")
	}
	if !noAnalysis {
		columns = append(columns, "AI ANALYSIS")
	}
	columns = append(columns, "TIMESTAMP")

	// Print header
	_, _ = fmt.Fprintln(w, strings.Join(columns, "\t"))

	// Rows
	for _, event := range events {
		row := formatEventRow(event, noAnalysis, showMetadata)
		_, _ = fmt.Fprintln(w, strings.Join(row, "\t"))
	}

	// Summary
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintf(w, "Total events: %d\n", len(events))

	return nil
}

// formatEventRow formats a single event as a slice of column values
func formatEventRow(event *models.Event, noAnalysis, showMetadata bool) []string {
	// Base columns
	resource := fmt.Sprintf("%s/%s", event.ResourceKind, event.ResourceName)
	namespace := "-"
	if event.Namespace != nil && *event.Namespace != "" {
		namespace = *event.Namespace
	}
	timestamp := event.EventTimestamp.Format("2006-01-02 15:04:05")

	row := []string{event.EventType, string(event.Severity), resource, namespace}

	// Optional metadata column
	if showMetadata {
		metadata := "-"
		if event.Metadata != nil {
			if metaJSON, err := json.Marshal(event.Metadata); err == nil {
				metaStr := string(metaJSON)
				if len(metaStr) > 40 {
					metaStr = metaStr[:37] + "..."
				}
				metadata = metaStr
			}
		}
		row = append(row, metadata)
	}

	// Optional AI analysis column
	if !noAnalysis {
		aiStatus := "No"
		if event.HasAIAnalysis() {
			aiStatus = "Yes"
		}
		row = append(row, aiStatus)
	}

	row = append(row, timestamp)
	return row
}

func outputJSON(events []*models.Event) error {
	encoder := json.NewEncoder(os.Stdout)
	encoder.SetIndent("", "  ")
	return encoder.Encode(events)
}

func outputYAML(events []*models.Event) error {
	data, err := yaml.Marshal(events)
	if err != nil {
		return fmt.Errorf("failed to marshal YAML: %w", err)
	}
	fmt.Println(string(data))
	return nil
}

func isValidSeverity(severity models.EventSeverity) bool {
	switch severity {
	case models.EventSeverityLow, models.EventSeverityMedium,
		models.EventSeverityHigh, models.EventSeverityCritical:
		return true
	default:
		return false
	}
}

func parseDuration(s string) (time.Duration, error) {
	// Support common suffixes like "24h", "7d", "30m"
	if strings.HasSuffix(s, "d") {
		// Parse days
		days := strings.TrimSuffix(s, "d")
		var d int
		_, err := fmt.Sscanf(days, "%d", &d)
		if err != nil {
			return 0, err
		}
		return time.Duration(d) * 24 * time.Hour, nil
	}

	// Otherwise use standard time.ParseDuration
	return time.ParseDuration(s)
}
